theme: jekyll-theme-cayman
title: ...
email: 'dev.yakuza@gmail.com'
description: ...
baseurl: ...
url: https://dev-yakuza.github.io
twitter_username: ...
github_username: ...
author: dev.yakuza@gmail.com

